// Mocks generated by Mockito 5.0.16 from annotations
// in recipe_app/test/features/recipe_book/domain/usecases/get_recipe_card_list_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:recipe_app/core/error/failures.dart' as _i5;
import 'package:recipe_app/features/recipe_book/domain/entities/recipe_card.dart'
    as _i6;
import 'package:recipe_app/features/recipe_book/domain/repositories/recipe_card_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [RecipeCardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeCardRepository extends _i1.Mock
    implements _i3.RecipeCardRepository {
  MockRecipeCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecipeCard>>>
      getRecipeCardList() => (super.noSuchMethod(
              Invocation.method(#getRecipeCardList, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.RecipeCard>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.RecipeCard>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecipeCard>>>);
  @override
  String toString() => super.toString();
}
